version: '2.1'
services:
  service:
    build:
      context: .
      dockerfile: ./framework-Dockerfile
    command: bash -c "python3 -m analyzer.cli --silent --docker"
    ports:
      - "5001:80"
    depends_on:
      - mongodb
    environment:
      - analyzer_env=docker
    networks:
      - backend
      - frontend
    volumes:
      - sharedfolder:/tmp/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  website:
    build:
      context: .
      dockerfile: ./webinterface-Dockerfile
    command: bash -c "/usr/local/bin/gunicorn --worker-class=gevent --worker-connections=1000 --workers=1 -b :8000 web:app"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - analyzer_env=docker
    networks:
      - frontend
      - backend
    volumes:
      - sharedfolder:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      disable: true 

  mongodb:
    build:
      context: .
      dockerfile: ./mongodb-Dockerfile
    ports:
      - '27017:27017'
    networks:
      - backend
      - frontend
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  sharedfolder:

networks:
  frontend:
    internal: false
  backend:
    internal: true
